name: Build

on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build php 7.4
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BASE_IMAGE=php:7.4-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lyralemos/php:7.4
      
      - name: Build php 8.2
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BASE_IMAGE=php:8.2-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lyralemos/php:latest,lyralemos/php:8.2
      
      - name: Build php 8.3
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BASE_IMAGE=php:8.3-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lyralemos/php:latest,lyralemos/php:8.3